name: Blue-Green Deploy

on:
  pull_request:
    types: [opened, reopened]
    branches: ["main"]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - uses: azure/setup-kubectl@v3
        id: install

      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
        id: setcontext
        
      - uses: Azure/k8s-deploy@v4
        with:
           namespace: 'default'
           manifests: |
            kubernetes-manifests/frontend.yaml
           strategy: blue-green
           action: deploy
           route-method: ingress
           version-switch-buffer: 5
           skip-tls-verify: true
