name: Blue-Green Promote/Reject

on:
  pull_request:
    types: [closed]
    branches: ["main"]

  workflow_dispatch:

jobs:

  Reject: 
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest

    steps:   
      - uses: actions/checkout@v3

      - uses: azure/setup-kubectl@v3
        id: install

      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
        id: setcontext

      - uses: Azure/k8s-deploy@v4
        with:
           namespace: 'default'
           manifests: |
            kubernetes-manifests/frontend.yaml
           strategy: blue-green
           route-method: ingress
           action: reject
           skip-tls-verify: true
  
  Promote: 
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: azure/setup-kubectl@v3
        id: install

      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
        id: setcontext

      - uses: Azure/k8s-deploy@v4
        with:
           namespace: 'default'
           manifests: |
            kubernetes-manifests/frontend.yaml
           strategy: blue-green
           action: promote
           skip-tls-verify: true